[package]
name = "feo-log"
version = "0.1.0"
edition = "2024"

[dependencies]
# The `std` feature is currently required for the `set_boxed_logger` call.
log = { workspace = true, features = ["std"] }

[dev-dependencies]
feo-logger = { workspace = true }
